# Generated by Django 4.2.30 on 2026-08-04 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_data', models.TextField(help_text='128-number face encoding, stored as JSON text')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Temporary text field — will link to a real Course model in Phase 3', max_length=200)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture (Manual)'), ('lab', 'Lab (Face-Locked)')], default='lecture', max_length=10)),
                ('session_date', models.DateField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, help_text='Lab session start (LAB mode only)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Lab session end (LAB mode only)', null=True)),
                ('allowed_ip_addresses', models.TextField(blank=True, help_text='Comma-separated IPs allowed to mark attendance (LAB mode only)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('marked_via', models.CharField(choices=[('face_match', 'Face Recognition (Lab)'), ('manual', 'Manual (Faculty)')], default='manual', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Face match distance score (lab sessions only, lower = better match)', null=True)),
                ('marked_from_ip', models.GenericIPAddressField(blank=True, help_text='IP address the request came from (lab sessions only)', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-marked_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
